# Hydra instantiation config for DIT model
_target_: discrete_diffusion.models.dit_candi.DIT_CANDI

# candi specific fields
mixed_coeff: 0.5 # coefficient for biasing strength 

# Legacy fields for backward compatibility
name: small_candi
type: ddit
hidden_size: 768
cond_dim: 128
length: 1024
n_blocks: 12
n_heads: 12
scale_by_sigma: True
dropout: 0.1
tie_word_embeddings: False
vocab_lookup: True
causal_attention: false
adaln: true
max_tokens: 1024
attn_type: full
attn_backend: flex